name: Update Widget list
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  update-widgets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update widget list
        run: |
          curl -s https://gristlabs.github.io/grist-widget/manifest.json | \
            jq \
              --argfile gl /dev/stdin \
              --argfile cur ./public/widget-list.json \
              -n '$cur + [($gl[] | select(([$gl[].url] - [$cur[].url])[] == .url))]' > ./public/widget-list.json2 \
              && mv ./public/widget-list.json{2,}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Mise à jour automatique de la liste des widgets de Grist Labs
          title: Mise à jour automatique de la liste des widgets de Grist Labs
          body: Mise à jour des widgets mises à disposition par Grist Labs et fusion avec nos propres widgets
          branch: update-widget-list
          base: main
